--Example:
SELECT
    SE."STUDENT-ID",
    SE."ENTITY-ID"


FROM PUB."STUDENT-ENTITY" SE

WHERE SE."X-DEFAULT-ENTITY" = 1
AND SE."STUDENT-STATUS" = 'I'
AND SE."ENTITY-ID" = ::campus_code::
AND SE."STUDENT-ID" IN (::at_risk_IDs::)

--[ TABLE-COLUMN-ALIAS MAP ]
--TABLE,COLUMN[,ALIAS]
--STUDENT-ENTITY,STUDENT-ID
--STUDENT-ENTITY,ENTITY-ID
--[ END MAP ]
